export const errorCode = {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    BAD_REQUEST: "BAD_REQUEST",
    NOT_FOUND: "NOT_FOUND",
    FORBIDDEN: "FORBIDDEN",
    INTERNAL: "INTERNAL_SERVER_ERROR"
};